config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user

    
    validates :title, presence: true, length: {minimum: 3, maximum: 25}
    validates :description, presence: true, length: {minimum: 10, maximum: 200}

    validates :user_id, presence: true #THE USER_ID IS REQUIRED FOR MAKE A POST NOW#

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :posts

    before_save { self.email.downcase!} #BEFORE SAVE https://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html 
                                        #"!" POUR QUE LE MAIL DEVIENNE EN MINUSCULE À 100%#
    validates :username, presence: true, 
                    length: {minimum: 3, maximum:15}, 
                    uniqueness: {case_sensitive: false}

    VALID_EMAIL_REGEX = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i #validation de l'email via txt@txt.fr

    validates :email, presence: true, 
            uniqueness: {case_sensitive: false},
            format: {with: VALID_EMAIL_REGEX}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


    def index  
        @posts = Post.all 
    end
    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user = User.first
        if @post.save
            flash[:success] = "Post crée"
            redirect_to post_path(@post)
        else
            render 'new'
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
        
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            flash[:success] = "Post mis à jour"
            redirect_to post_path(@post)
        else
            render 'edit'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        flash[:success] = "Post supprimé"
        redirect_to posts_path
    end


  
    private

    def post_params
        params.require(:post).permit(:title, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<section>
    <div class="container">
        <footer>
            <small>
                <a href="https://www.youtube.com/watch?v=iv8GW1GaoIc", title="The Doors", target="_blank"> The Doors</a>
            </small>
            <nav>
                <ul>
                    <li><a href="https://www.linkedin.com/in/harry-knight-134679182/" target="_blank" >Linkedin</a></li>
                    <li><%= link_to "Posts",posts_path, class:"text-success"%></li>
                </ul>
            </nav>
        </footer>
    </div>
</section>

app/views/layouts/_message.html.erb
<!-- Message de mise à jours/nouveau post -->
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-8 col-xs-offset-4">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%= "#{name}" %>'>
          <a href="#", class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash-#{name}" if msg.is_a?(String)%>  
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<section>
    <nav class="navbar navbar-expand-lg navbar-light bg-success">
        <%= link_to 'Health Crew', root_path, class: "navbar-brand font-weight-bold", id:"logo"%>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Actions
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Mon compte</a>
                        <a class="dropdown-item" href="#">Mes posts</a>
                        <a class="dropdown-item" href="#">Me déconnecter</a>
                    </div>
                </li>
                <li class="nav-item">
                    <%= link_to 'Posts', posts_path, class:'nav-link'%>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Idées</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Membres actifs</a>
                </li>
            </ul>
        </div>
    </nav>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PictureApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/message'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/home.html.erb
<section>
    <div class="center">
        <div class="jumbotron">
        <h1 class="display-4 pt-5 font-weight-bold">Health Crew</h1>
        <hr class="my-4">
        <p class="font-weight-bold text-uppercase">Bienvenu parmi notre communautée de sportifs de tous niveaux</p>
        <%= link_to 'Sinscrire', '#', class:"btn btn-success btn-lg"%>
        </div>
    </div>
</section>

<section id="info" class="py-5">
    <div class="container">
        <div class="row">
            <div id="txtLaptop" class="col-md-6 align-self-center">
                <h3>Pourquoi rejoindre notre communautée ?</h3>
                <p>
                    Nous partageons des valeurs sportives quelque soit la discipline ainsi que notre savoir et l'envie d'apprendre de nouvelles
                    choses entre nous.
                </p>
                <p>
                Un discord est mis en place pour des échanges plus rapides entres chaque utilisateurs. 
                </p>
                <a href="https://discord.gg/2zvA2wJ" target="_blank" class="btn btn-outline-dark">Rejoindre le Discord</a>
            </div>
            <div class="col-md-6">
            <p class="offset-3"><%= image_tag("discordus.png",size: "150x150", :alt => "logo discord health crew") %><p>
            </div>
        </div>
    </div>
</section>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-5 col-md-offset-5 col-sm-6">
            <%= form_for(@post, :html => {class: "form-horizontal", role: "form"}) do |f|%>
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title,  class:"form-control", placeholder:"Titre"%>
                </div>
                <div class="form-group">
                        <%= f.label :description %>
                        <%= f.text_area :description, rows: 10,  class:"form-control", placeholder:"Description du post"%>
                </div>
                <div class="form-group">
                        <%= f.label :image %>
                        <%= f.text_field :image, type:"file", class: "btn btn-success form-control-file", placeholder:"Photo" %>
                </div>
                <div class="form-group">
                    <%= f.submit class:"btn btn-outline-success"%>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/posts/edit.html.erb
<div class="row justify-content-center">
    <h1 class="pt-3">Edit post<h1>
</div>
<%= render 'posts/form'%>

app/views/posts/index.html.erb
<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xs-9 col-xs-offset-6 p-3">
                <h1>Posts </h1>
                <p><%= link_to 'New post', new_post_path, class:'btn btn-sm btn-outline-success' %>
                </p>
                    <table class="table table-borderless">
                        <thead>
                            <tr>
                                <th>Titre</th>
                                <th>Description</th>
                                <th>Image</th>
                                <th>Actions</th>
                            </tr>
                        </thead>    
                        <% @posts.each do |post|%>
                        <tbody>
                            <tr>
                                <td><%= link_to post.title, post_path(post) %></td>
                                <td><%= truncate(post.description, length: 55) %></td> <!-- truncate + length pour "..." en cas ou description trop longue-->
                                <td><%= post.image %></td>
                                <td><%= link_to 'Edit', edit_post_path(post), class:"btn btn-outline-primary" %></td>
                                <td><%= link_to 'Show', post_path(post), class:"btn btn-outline-info" %></td>
                                <td><%= link_to 'Delet', post_path(post), method: :delete, class:"btn btn-outline-danger" %></td>
                            </tr>
                        <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
    </div>
</section>

app/views/posts/new.html.erb
<div class="row justify-content-center">
    <h1 class="pt-3">Nouveau post <h1>
</div>

<%= render 'posts/form'%>

app/views/posts/show.html.erb
<div class="container">
    <div class="row justify-content-center p-5">
        <div class="col-sm-9">
            <div class="card">

                <div class="card-header">
                    <h2><%= @post.title %></h2>
                </div>
                <div class="card-body">
                    <p class="card-text"> <%= @post.description %></p>
                      <img src="..." class="card-img-top" alt="..."> <!-- <p><%= @post.image %></p> FIREBASE IMG-->
                </div>
                <div class="card-footer text-muted">
                    <!-- Timestamps -->
                </div>
            </div>
            <div class="pt-1">
                <div class="col-offset-4 pt-2">
                <%= link_to 'Posts', posts_path, class:"btn btn-outline-success" %> 
                <%= link_to 'Edit this post', edit_post_path(@post), class:"btn btn-outline-info" %> 
                <%= link_to 'Delet', post_path(@post), method: :delete, class:"btn btn-outline-danger" %> 
            </div>
        </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row justify-content-center" role="alert">
        <div class="col-xs-8">
            <div class="alert alert-danger">
                <div class="panel-heading">
                    <h2 class="alert-title">
                    <%= pluralize(obj.errors.count, "erreur") %>
                    </h2>
                </div>
                <div class="alert-body"></div>
                    <% obj.errors.full_messages.each do |msg| %>
                            <ul>
                                <li> <%= msg %> </li>
                            </ul>
                    <% end%>
                </div>
            </div>
        </div>
    </div>
<% end %>